- name: DEBIAN | Require fish >= 3 on Debian >= 10
  fail:
    msg: Only fish >= 3 is supported on Debian >= 10
  when:
    - ansible_facts.distribution == 'Debian'
    - fish_release_version is version('3', '<')
    - ansible_facts.distribution_major_version is version('10', '>=')
  tags:
    - fish

- name: DEBIAN | Add fish repository key
  get_url:
    url: "{{ _fish_apt_key_url }}"
    dest: /etc/apt/trusted.gpg.d/shells_fish_release_{{ fish_release_version }}.asc
  tags:
    - fish

- name: DEBIAN | Add fish repository
  apt_repository:
    filename: shells_fish_release_{{ fish_release_version }}
    repo: "{{ _fish_apt_repo_url }}"
  tags:
    - fish

- name: DEBIAN | Install fish
  apt:
    name: fish
    allow_unauthenticated: yes
    state: latest
    cache_valid_time: 600
  tags:
    - fish
