- name: RHEL | Create yum repo
  yum_repository:
    name: shells_fish_release_2
    description: Fish shell - 2.x release series ({{ fish_repo_version_string }})
    baseurl: http://download.opensuse.org/repositories/shells:/fish:/release:/2/{{ fish_repo_version_string }}/
    gpgkey: http://download.opensuse.org/repositories/shells:/fish:/release:/2/{{ fish_repo_version_string }}/repodata/repomd.xml.key
    enabled: true
    gpgcheck: true
    file: fish
  tags:
    - fish

- name: RHEL | Install Fish
  action: "{{ ansible_facts.pkg_mgr }}"
  args:
    name: fish
    state: latest
  tags:
    - fish
