- name: DEBIAN | Add fish repository key
  apt_key:
    keyserver: "{{ fish_apt_keyserver | default(omit) }}"
    url: "{{ fish_apt_key_url | default(omit) }}"
    id: "{{ fish_apt_key_id | default(omit) }}"
    state: present
  tags:
    - fish

- name: DEBIAN | Add fish repository
  apt_repository:
    filename: shells_fish_release_{{ fish_release_version }}
    repo: "{{ fish_apt_repo_url }}"
  tags:
    - fish

- name: DEBIAN | Install fish
  apt:
    name: fish
    allow_unauthenticated: true
    state: latest
    cache_valid_time: 600
  tags:
    - fish
