- name: DEBIAN | Add fish repository
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_{{ ansible_facts.distribution_major_version }}.0/ /

- name: DEBIAN | Install fish
  apt:
    name: fish
    allow_unauthenticated: true
    state: latest
    cache_valid_time: 600
