- name: RHEL | Create yum repo
  yum_repository:
    name: shells_fish_release_{{ fish_release_version }}
    description: Fish shell - {{ fish_release_version }}.x release series ({{ fish_repo_version_string }})
    baseurl: http://download.opensuse.org/repositories/shells:/fish:/release:/{{ fish_release_version }}/{{ fish_repo_version_string }}/
    gpgkey: http://download.opensuse.org/repositories/shells:/fish:/release:/{{ fish_release_version }}/{{ fish_repo_version_string }}/repodata/repomd.xml.key
    enabled: yes
    gpgcheck: yes
    file: fish
  tags:
    - fish

- name: RHEL | Install Fish
  action: "{{ ansible_facts.pkg_mgr }}"
  args:
    name: fish
    state: latest
  tags:
    - fish
