- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.os_distribution }}.yml"
    - main.yml

- include: "install-{{ ansible_facts.os_family }}.yml"
